name: Build LaTeX document
on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  discussions: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: thesis.pdf
  release:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Download PDF file
        uses: actions/download-artifact@v4
        with:
          name: PDF
          path: .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            thesis.pdf
            LICENSE
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            [View PDF](${{ github.server_url }}/${{ github.repository }}/raw/${{ github.ref }}/thesis.pdf)
