name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.aux
          compiler: bibtex
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
